### ISSUE TITLE
Convert PUSH_OPENSSL_ERROR to a function-like macro

### ISSUE THREAD

**Issue by rillig** [lavabit/libcommon#10]
Instead of `PUSH_OPENSSL_ERROR;`, the code should look like `PUSH_OPENSSL_ERROR();`, so that source code analyzers like the Eclipse source code formatter don’t get confused.

Since function-like macros follow a long tradition, this change also helps human readers to better understand the code.

    #define PUSH_ERROR_OPENSSL() do { ... } while 0

**Comment by LBiv** [comment]
Done.
