### ISSUE TITLE
ed25519.h not found

### ISSUE THREAD

**Issue by 0-wiz-0** [lavabit/libcommon#21]
Compilation stops because ed25519.h is not found. README.md only mentions zlib and openssl; AFAIK neither of those provide this header file. Where is it supposed to come from?

````
Building libraries...
gmake -C lib all
gmake[1]: Entering directory '/archive/foreign/lavabit/libcommon/lib'
test -d .objs || mkdir .objs
test -d .deps || mkdir .deps
Compiling..
gcc -M -MF .deps/crypto.d.tmp -Wall -Werror -ggdb -I../include -I../providers/sources/donna/ -fPIC -c crypto.c
In file included from crypto.c:9:0:
../include/dcrypto.h:10:21: fatal error: ed25519.h: No such file or directory
 #include "ed25519.h"
                     ^
compilation terminated.
../Makefile.rules:7: recipe for target '.objs/crypto.o' failed
````

**Comment by LBiv** [comment]
ed25519.h comes from donna, which is a crypto library containing the ed25519 signing curve.

Try running build.sh from libcommon/providers before running make.

**Comment by 0-wiz-0** [comment]
Ok, thanks.  I had given up on build.sh because it insists on building openssl and I want to use the one provided by the base system; but when I comment out the openssl lines from build.sh, donna is built and found.
