### ISSUE TITLE
isspace needs unsigned char argument

### ISSUE THREAD

**Issue by 0-wiz-0** [lavabit/libcommon#22]
Compilation on NetBSD fails because of -Werror and:
misc.c:1276:5:error: array subscript has type 'char'
and the same problem in lines 1309 and 1344.

The easiest fix is to just add a (unsigned char) cast.

See http://netbsd.gw.com/cgi-bin/man-cgi?ctype+3+NetBSD-current for details why this is needed.

**Comment by LBiv** [comment]
fixed
