### ISSUE TITLE
missing NUL terminator

### ISSUE THREAD

**Issue by MegaManSec** [lavabit/libcommon#3]
Hi,

In /lib/error.c:

367                strncpy(errptr->filename, filename, sizeof(errptr->filename));
371                strncpy(errptr->funcname, funcname, sizeof(errptr->funcname));
375                strncpy(errptr->auxmsg, auxmsg, sizeof(errptr->auxmsg));

all may not be NUL terminated. Deliberate? May want to check.

**Comment by rillig** [comment]
Fixed in a55a1700287341377eaacf09468e4e1f796ae671.

**Comment by LBiv** [comment]
ty
